image: debian:bullseye
run-as-user: madlinux

#variables:
#  ENV: value

#before_script:
#  - gem install bundler

#after_script:
#  - command

repo:
  stage: deploy
  script:
    - whoami
#  - bash build.sh
  only:
  - main