image: ubuntu:focal

before_script:
  - apt update
  - apt install -y gnupg
  - echo 'deb http://ppa.launchpad.net/apt-fast/stable/ubuntu bionic main'|tee /etc/apt/sources.list.d/apt-fast.list
  - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A2166B8DE8BDC3367D1901C11EE2FF37CA8DA16B
  - apt update
  - apt install -y apt-fast
  - |
    apt-fast install -y \
      aria2 \
      build-essential \
      checkinstall \
      dpkg-sig \
      git \
      reprepro \
      sshpass \
      wget

job:
  script:
  - bash build.sh
  only:
  - main