image:
  name: debian:bullseye
  entrypoint: ['bash', '-c', 'useradd madlinux && exec su madlinux -c bash']

#variables:
#  ENV: value

before_script:
  - sudo apt update
  - sudo apt install -y gnupg
  - sudo echo 'deb http://ppa.launchpad.net/apt-fast/stable/ubuntu bionic main'|tee /etc/apt/sources.list.d/apt-fast.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A2166B8DE8BDC3367D1901C11EE2FF37CA8DA16B
  - sudo apt update
  - sudo apt install -y apt-fast
  - |
    sudo apt-fast install -y \
      aria2 \
      build-essential \
      checkinstall \
      dpkg-sig \
      git \
      reprepro \
      sshpass \
      wget

#after_script:
#  - echo "After script section"
#  - echo "For example you might do some cleanup here"

job:
  script:
  - bash build.sh
  only:
  - main