image: debian:latest

before_script:
  - cat /etc/apt/sources.list|grep 'deb http'
  - ls -1 /etc/apt/sources.list.d/
  - | 
    sudo rm -rfv \
      /etc/apt/sources.list.d/azure-cli.list* \
      /etc/apt/sources.list.d/bazel.list* \
      /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list* \
      /etc/apt/sources.list.d/git-core-ubuntu-ppa-focal.list* \
      /etc/apt/sources.list.d/github_git-lfs.list* \
      /etc/apt/sources.list.d/google*.list* \
      /etc/apt/sources.list.d/heroku.list* \
      /etc/apt/sources.list.d/hvr-ubuntu-ghc-focal.list* \
      /etc/apt/sources.list.d/kubernetes.list* \
      /etc/apt/sources.list.d/microsoft-prod.list* \
      /etc/apt/sources.list.d/mongodb-org-4.4.list* \
      /etc/apt/sources.list.d/mono-official-stable.list* \
      /etc/apt/sources.list.d/pgdg.list* \
      /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-focal.list*
  - sudo apt update

job:
  script:
  - sudo apt install -y build-essential checkinstall dpkg-sig reprepro sshpass
  - bash build.sh
  only:
  - main