image:
  name: ubuntu:focal
  entrypoint: ['bash', '-c', 'apt update && apt install -y sudo && useradd madlinux && usermod -a -G sudo madlinux && echo "madlinux ALL=(ALL) NOPASSWD:ALL"|tee /etc/sudoers.d/madlinux && exec su madlinux -c bash']

#variables:
#  ENV: value

before_script:
  - sudo apt update
  - sudo apt install -y gnupg
  - echo 'deb http://ppa.launchpad.net/apt-fast/stable/ubuntu bionic main'|sudo tee /etc/apt/sources.list.d/apt-fast.list
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A2166B8DE8BDC3367D1901C11EE2FF37CA8DA16B
  - sudo apt update
  - sudo apt install -y apt-fast
  - sudo sed -i 's/_APTMGR=apt-get/_APTMGR=apt/g' /etc/apt-fast.conf
  - sudo dpkg --add-architecture i386
  - sudo apt update
  - |
    apt-fast install -y \
      aria2 \
      build-essential \
      checkinstall \
      dpkg-sig \
      git \
      reprepro \
      sshpass \
      sudo \
      wget
  - sudo chmod -R 777 /home/madlinux
#  - aria2c ${{ secrets.GPG_SEC }}
#  - gpg --batch --allow-secret-key-import --import madlinux_sec.gpg
  - |
    wget -qO- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-amd64/Packages|grep \
      'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-amd64-1.log
    wget -qO- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-i386/Packages|grep \
      'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-i386-1.log


#after_script:
#  - |
#    sshpass -p ${{ secrets.SOURCEFORGE_PASS }} -- \
#    rsync -avP --del -e 'ssh -o StrictHostKeyChecking=no' \
#    repo rauldipeas@frs.sourceforge.net:/home/frs/project/madlinux
#  - |
#    wget -qO- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-amd64/Packages|grep \
#      'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-amd64-2.log
#    wget -qO- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-i386/Packages|grep \
#      'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-i386-2.log


madrepo:
  script:
  - bash build.sh
  only:
  - main