image:
  name: debian:bullseye
  entrypoint: ['bash', '-c', 'useradd madlinux && exec su madlinux -c bash']

#variables:
#  ENV: value

#before_script:
#  - gem install bundler

#after_script:
#  - command

repo:
  stage: deploy
  script:
    - whoami
#  - bash build.sh
  only:
  - main