pool:
  vmImage: 'ubuntu-20.04'

trigger:
  branches:
    include: [ master ]

schedules:
  - cron: "0 0,6,12,18 * * *"
    displayName: Compilação recorrente do repositório apt do MAD Linux
    branches:
      include: [ master ]

variables:
  - group: Tokens

steps:
  - script: |
      sudo sed -i 's/_APTMGR=apt-get/_APTMGR=apt/g' /etc/apt-fast.conf
      sudo dpkg --add-architecture i386
    displayName: Configuração do host

  - script: |
      aria2c $GPG_SEC
      gpg --batch --allow-secret-key-import --import madlinux_sec.gpg
    displayName: Instalação da chave GPG

  - script: sudo apt-fast install -y checkinstall dpkg-sig reprepro sshpass
    displayName: Instalação de dependências

  - script: bash build.sh
    displayName: Compilação do repositório apt do MAD Linux

  - script: sshpass -p $SOURCEFORGE_PASS -- rsync -avP -e 'ssh -o StrictHostKeyChecking=no' repo rauldipeas@web.sourceforge.net:/home/project-web/madlinux/htdocs
    displayName: Upload do repositório apt do MAD Linux para o SourceForge