name: MAD Repo
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'readme.md'
      - 'TODO'
  schedule:
  - cron: "0 0,6,12,18 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Verificação de saída do repositório git
        uses: actions/checkout@v1

      - name: Indetificação do avatar de status para o Guilded
        id: guilded-avatar
        run: |
          avatar_url=$(cat assets/guilded-avatar.json | jq '.${{ job.status }}')
          echo '::set-output name=avatar_url::${avatar_url}'

      - name: Indetificação da descrição de status para o Guilded
        id: guilded-description
        run: |
          description=$(cat assets/guilded-description.json | jq '.${{ job.status }}')
          echo '::set-output name=description::${description}'
  
      - name: Notificação para o Guilded
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.GUILDED_WEBHOOK }}
          noprefix: true
          title: "Compilação do repositório `apt` do **MAD Linux**"
          description: ${{ steps.guilded-description.outputs.description }}
          status: ${{ job.status }}
          username: GitHub Actions
          avatar_url: ${{ steps.guilded-avatar.outputs.avatar_url }}