name: MAD Repo
on:
  push:
    branches: 
      - master
  schedule:
  - cron: "0 0,6,12,18 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Verificação de saída do repositório git
        uses: actions/checkout@v1
      
      - name: Configuração do host
        run: |
          sudo sed -i 's/_APTMGR=apt-get/_APTMGR=apt/g' /etc/apt-fast.conf
          sudo dpkg --add-architecture i386
      
      - name: Instalação da chave GPG
        run: |
          aria2c ${{ secrets.GPG_SEC }}
          gpg --batch --allow-secret-key-import --import madlinux_sec.gpg
      
      - name: Instalação de dependências
        run: |
          sudo apt update
          sudo apt-fast install -y build-essential checkinstall dpkg-sig reprepro sshpass

      - name: Compilação do repositório apt
        run: bash build.sh
#        env:
#          BASHRUN_GL_TOKEN: ${{ secrets.BASHRUN_GL_TOKEN }}

      - name: Upload do repositório apt para o SourceForge
        run: |
          sshpass -p ${{ secrets.SOURCEFORGE_PASS }} -- \
          rsync -avP --del -e 'ssh -o StrictHostKeyChecking=no' \
          repo rauldipeas@web.sourceforge.net:/home/project-web/madlinux/htdocs