name: MAD Repo
on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'readme.md'
      - 'TODO'
  schedule:
  - cron: "0 0,6,12,18 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Verificação de saída do repositório git
        uses: actions/checkout@v1

#      - name: Notificação para o Element
#        run: |
#          git clone https://github.com/saadnpq/matrixcli
#          cd matrixcli
#          sudo ./install.sh
#          mkdir -pv ~/.config/matrixcli
#          echo 'def password_eval():
#              return ""
#          accounts=[{ "server":"https://matrix.org", "username":"raul_dipeas", "passeval":password_eval }]'|tee ~/.config/matrixcli/config.py
#          matrixcli -u raul_dipeas -p ${{ secrets.MATRIX_PASS }} send -r '!knBRYnXnZPjrUESyac:matrix.org' 'GitHub Actions ${{ github.workflow }} with commit ${{ github.sha }} build with ${{ job.status }} https://gitlab.com/myawesomedistro/madrepo'
      
      - name: Notificação para o Telegram
        uses: appleboy/telegram-action@master
        with:
          to: -1001267848465
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: O repositório `[apt](https://gitlab.com/myawesomedistro/madrepo)` do *MAD Linux* acaba de ser compilado no *GitHub Actions* com status *[${{ job.status }}](https://actions-badge.atrox.dev/myawesomedistro/madrepo/goto)* https://gitlab.com/myawesomedistro/madrepo/-/commit/{{ commit.sha }}