name: MAD Repo
on:
  push:
    branches: 
      - master
  schedule:
  - cron: "0 0,6,12,18 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Verificação de saída do repositório git
        uses: actions/checkout@v1
      
      - name: Configuração do host
        run: |
          sudo sed -i 's/_APTMGR=apt-get/_APTMGR=apt/g' /etc/apt-fast.conf
          sudo dpkg --add-architecture i386
      
      - name: Instalação da chave GPG
        run: |
          aria2c ${{ secrets.GPG_SEC }}
          gpg --batch --allow-secret-key-import --import madlinux_sec.gpg
      
      - name: Instalação de dependências
        run: sudo apt-fast install -y checkinstall dpkg-sig reprepro shc sshpass

      - name: Compilação do Bashrun
        run: |
          git clone https://gitlab.com/myawesomedistro/bashrun
          cd bashrun
          sed -i "s/BASHRUN_GL_TOKEN/${{ secrets.BASHRUN_GL_TOKEN }}/g" usr/bin/bashrun-url
          cat usr/bin/bashrun-url
          shc -f usr/bin/bashrun-url -o usr/bin/bashrun-url
          rm usr/bin/bashrun-url.x.c
          BASHRUN_TAG=`echo $(git describe --always --dirty)-$(git log -1 --date=iso --pretty=format:%cd)|sed 's/\ /-/g'|sed 's/v//g'|sed 's/_/-/g'|sed 's/:/-/g'|sed 's/dirty-//g'|cut -d '-' -f2-7`
          sed -i "s/TAG/$BASHRUN_TAG/g" DEBIAN/control
          rm -rf .git
          cd ..
          dpkg-deb -b bashrun .

      - name: Compilação do repositório apt
        run: bash build.sh

      - name: Upload do repositório apt para o SourceForge
        run: |
          sshpass -p ${{ secrets.SOURCEFORGE_PASS }} -- \
          rsync -avP --del -e 'ssh -o StrictHostKeyChecking=no' \
          repo rauldipeas@web.sourceforge.net:/home/project-web/madlinux/htdocs