name: MAD Repo
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'readme.md'
      - 'TODO'
  schedule:
  - cron: "0 0,6,12,18 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Verificação de saída do repositório git
        uses: actions/checkout@v1

      - name: Configuração do host
        run: |
            sudo sed -i 's/_APTMGR=apt-get/_APTMGR=apt/g' /etc/apt-fast.conf
            sudo dpkg --add-architecture i386

      - name: Instalação da chave GPG
        run: |
            aria2c ${{ secrets.GPG_SEC }}
            gpg --batch --allow-secret-key-import --import madlinux_sec.gpg

      - name: Instalação de dependências
        run: |
            sudo apt update
            sudo apt-fast install -y build-essential checkinstall dpkg-sig reprepro sshpass

      - name: Download das informações de estado do repositório
        run: |
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-amd64/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-amd64-1.log
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-i386/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-i386-1.log

      - name: Compilação do repositório apt
        run: bash build.sh
#        env:
#            BASHRUN_GL_TOKEN: ${{ secrets.BASHRUN_GL_TOKEN }}

      - name: Upload do repositório apt para o SourceForge Web
            sshpass -p ${{ secrets.SOURCEFORGE_PASS }} -- \
            rsync -avP --del -e 'ssh -o StrictHostKeyChecking=no' \
            repo rauldipeas@web.sourceforge.net:/home/project-web/madlinux/htdocs

      - name: Upload do repositório apt para o SourceForge FRS
        run: |
            sshpass -p ${{ secrets.SOURCEFORGE_PASS }} -- \
            rsync -avP --del -e 'ssh -o StrictHostKeyChecking=no' \
            repo rauldipeas@frs.sourceforge.net:/home/frs/project/madlinux

      - name: Download das informações de estado do repositório
        run: |
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-amd64/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-amd64-2.log
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-i386/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-i386-2.log

      - name: Comparação do estado dos pacotes amd64
        uses: LouisBrunner/diff-action@v0.1.0
        with:
            old: packages-amd64-1.log
            new: packages-amd64-2.log
            mode: addition
            tolerance: mixed
            output: pacotes-amd64.txt

      - name: Comparação do estado dos pacotes i386
        uses: LouisBrunner/diff-action@v0.1.0
        with:
            old: packages-i386-1.log
            new: packages-i386-2.log
            mode: addition
            tolerance: mixed
            output: pacotes-i386.txt

      - name: Compactação dos arquivos de log
        uses: papeloto/action-zip@v1
        with:
            files: pacotes-amd64.txt pacotes-i386.txt
            dest: pacotes.zip

      - name: Notificação para o Telegram
        uses: appleboy/telegram-action@master
        with:
            to: -1001267848465
            token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
            format: markdown
            message: "O repositório [apt](https://gitlab.com/myawesomedistro/madrepo) do *MAD Linux* acaba de ser compilado no *GitHub Actions* com status: [${{ job.status }}](https://actions-badge.atrox.dev/myawesomedistro/madrepo/goto)\n\nVeja o `commit` de referência neste link:\n\nhttps://gitlab.com/myawesomedistro/madrepo/-/commit/{{ commit.sha }}.\n\nConfira os pacotes adicionados e removidos no arquivo `pacotes.zip`."
            document: pacotes.zip