name: MAD Repo Cleanup Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'readme.md'
      - 'TODO'
  schedule:
  - cron: "0 0,6,12,18 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Verificação de saída do repositório git
        uses: actions/checkout@v1
      
      - name: Liberação de espaço em disco
        run: |
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          sudo apt autoremove --purge -y '^ghc-8.*' '^dotnet-.*' '^llvm-.*' azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
          sudo apt clean
          df -h
          rm -rf /usr/share/dotnet/
          df -h
          sudo swapoff -a
          sudo rm -f /swapfile
          df -h
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h