name: MAD Repo
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'readme.md'
      - 'TODO'
  schedule:
  - cron: "0 0,6,12,18 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Verificação de saída do repositório git
        uses: actions/checkout@v1

      - name: Liberação de espaço em disco
        run: |
          df -h
          sudo apt autoremove --purge -y \
            azure-cli \
            '^dotnet-.*' \
            firefox \
            '^ghc-8.*' \
            google-chrome-stable \
            google-cloud-sdk \
            hhvm \
            '^llvm-.*' \
            powershell \
            snapd
          sudo apt clean
          sudo swapoff -a
          sudo rm -rf \
            "$AGENT_TOOLSDIRECTORY" \
            /opt/az \
            /swapfile \
            /usr/share/dotnet \
            /usr/local/share/boost
          df -h
      
      - name: Checagem dos repositórios
        run: |
          cat /etc/apt/sources.list|grep 'deb http'
          ls -1 /etc/apt/sources.list.d/
          sudo rm -rfv \
            /etc/apt/sources.list.d/azure-cli.list* \
            /etc/apt/sources.list.d/bazel.list* \
            /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list* \
            /etc/apt/sources.list.d/git-core-ubuntu-ppa-focal.list* \
            /etc/apt/sources.list.d/github_git-lfs.list* \
            /etc/apt/sources.list.d/google*.list* \
            /etc/apt/sources.list.d/heroku.list* \
            /etc/apt/sources.list.d/hvr-ubuntu-ghc-focal.list* \
            /etc/apt/sources.list.d/kubernetes.list* \
            /etc/apt/sources.list.d/microsoft-prod.list* \
            /etc/apt/sources.list.d/mongodb-org-4.4.list* \
            /etc/apt/sources.list.d/mono-official-stable.list* \
            /etc/apt/sources.list.d/pgdg.list* \
            /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-focal.list*
          apt-fast update

      - name: Configuração do host
        run: |
          sudo sed -i 's/_APTMGR=apt-get/_APTMGR=apt/g' /etc/apt-fast.conf
          sudo dpkg --add-architecture i386

      - name: Instalação da chave GPG
        run: |
          aria2c ${{ secrets.GPG_SEC }}
          gpg --batch --allow-secret-key-import --import madlinux_sec.gpg

      - name: Instalação de dependências
        run: |
          apt-fast update -qq 2>/dev/null
          apt-fast install -y build-essential curl checkinstall dpkg-sig reprepro sshpass 2>/dev/null

      - name: Download das informações de estado do repositório
        run: |
          wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-amd64/Packages|grep \
          'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-amd64-1.log
          wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-i386/Packages|grep \
          'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-i386-1.log

      - name: Compilação do repositório apt
        run: |
          export GAPI_AUTH=${{ secrets.GAPI_ID }}:${{ secrets.GAPI_TOKEN }}
          bash build.sh

      - name: Upload do repositório apt para o SourceForge FRS
        run: |
          sshpass -p ${{ secrets.SOURCEFORGE_PASS }} -- \
          rsync -avP --del -e 'ssh -o StrictHostKeyChecking=no' \
          repo rauldipeas@frs.sourceforge.net:/home/frs/project/madlinux

      - name: Download das informações de estado do repositório
        run: |
          wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-amd64/Packages|grep \
          'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-amd64-2.log
          wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-i386/Packages|grep \
          'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-i386-2.log

      - name: Comparação do estado dos pacotes amd64
        uses: LouisBrunner/diff-action@v0.1.0
        with:
          old: packages-amd64-1.log
          new: packages-amd64-2.log
          mode: addition
          tolerance: mixed-worse
          output: pacotes-amd64.txt

      - name: Comparação do estado dos pacotes i386
        uses: LouisBrunner/diff-action@v0.1.0
        with:
          old: packages-i386-1.log
          new: packages-i386-2.log
          mode: addition
          tolerance: mixed-worse
          output: pacotes-i386.txt

      - name: Conteúdo atualizado do repositório
        run: |
          echo '```'>>madrepo.md
          cat pacotes-amd64.txt>>madrepo.md
          echo '```'>>madrepo.md
          echo '```'>>madrepo.md
          cat pacotes-i386.txt>>madrepo.md
          echo '```'>>madrepo.md

      - name: Upload do log para o GitHub Gist
        uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/rauldipeas/103d3d1558cba200b828a710aaf50549
          gist_title: madrepo.md
          gist_description: Pacotes adicionados e removidos na última atualização do repositório apt do MAD Linux
          github_file: madrepo.md

      - name: Notificação de sucesso para o Guilded
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.GUILDED_WEBHOOK }}
          noprefix: true
          title: "Compilação do repositório `apt` do **MAD Linux**"
          description: "O repositório [apt](https://gitlab.com/myawesomedistro/madrepo) do **MAD Linux** acaba de ser compilado no *GitHub Actions*\n\nConfira os pacotes adicionados e removidos [neste link](https://gist.github.com/rauldipeas/103d3d1558cba200b828a710aaf50549)"
          status: ${{ job.status }}
          username: GitHub Actions
          avatar_url: https://www.polifitema.com.br/wp-content/uploads/2017/02/success-icon-7.png

      - name: Notificação de erro para o Guilded
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.GUILDED_WEBHOOK }}
          noprefix: true
          title: "Compilação do repositório `apt` do **MAD Linux**"
          description: "Houve um erro na compilação do repositório [apt](https://gitlab.com/myawesomedistro/madrepo) do **MAD Linux** no *GitHub Actions*"
          status: ${{ job.status }}
          username: GitHub Actions
          avatar_url: https://iconsplace.com/wp-content/uploads/_icons/ff0000/256/png/error-icon-14-256.png

      - name: Notificação de cancelamento para o Guilded
        uses: sarisia/actions-status-discord@v1
        if: cancelled()
        with:
          webhook: ${{ secrets.GUILDED_WEBHOOK }}
          noprefix: true
          title: "Compilação do repositório `apt` do **MAD Linux**"
          description: "A compilação do repositório [apt](https://gitlab.com/myawesomedistro/madrepo) do **MAD Linux** foi cancelada no *GitHub Actions*"
          status: ${{ job.status }}
          username: GitHub Actions
          avatar_url: https://zeromilefashion.com/wp-content/uploads/2019/01/disclaimer-icon.png