name: MAD Repo Diff
on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'readme.md'
      - 'TODO'
  schedule:
  - cron: "0 0,6,12,18 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:      
      - name: Download das informações de estado do repositório
        run: |
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-amd64/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-amd64-1.log
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-i386/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-i386-1.log
            sleep 120
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-amd64/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-amd64-2.log
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-i386/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-i386-2.log

      - name: Comparação do estado dos pacotes `amd64`
        uses: LouisBrunner/diff-action@v0.1.0
          with:
            old: packages-amd64-1.log
            new: packages-amd64-2.log
            mode: addition
            tolerance: better
            output: packages-amd64.txt

      - name: Comparação do estado dos pacotes `i386`
        uses: LouisBrunner/diff-action@v0.1.0
          with:
            old: packages-i386-1.log
            new: packages-i386-2.log
            mode: addition
            tolerance: better
            output: packages-i386.txt