name: MAD Repo Diff
on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'readme.md'
      - 'TODO'
  schedule:
  - cron: "0 0,6,12,18 * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:      
      - name: Checagem dos pacotes
        run: |
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-amd64/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-amd64-`date +'%d-%m-%Y-%H-%M'`.log
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-i386/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-i386-`date +'%d-%m-%Y-%H-%M'`.log
            sleep 120
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-amd64/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-amd64-`date +'%d-%m-%Y-%H-%M'`.log
            wget -O- https://sourceforge.net/projects/madlinux/files/repo/dists/core/main/binary-i386/Packages|grep 'Package:\|Version:'|sed ':a;N;$!ba;s/\nVersion://g'|sed 's/Package: //g'>packages-i386-`date +'%d-%m-%Y-%H-%M'`.log
            diff --new-line-format="+ %L" --old-line-format="- %L" --unchanged-line-format="= %L" `ls packages-amd64*`|grep '+ ' > packages.log
            diff --new-line-format="+ %L" --old-line-format="- %L" --unchanged-line-format="= %L" `ls packages-amd64*`|grep '\- ' >> packages.log
            diff --new-line-format="+ %L" --old-line-format="- %L" --unchanged-line-format="%L" `ls packages-i386*`|grep '+ ' >> packages.log
            diff --new-line-format="+ %L" --old-line-format="- %L" --unchanged-line-format="%L" `ls packages-i386*`|grep '\- ' >> packages.log7